apiVersion: v1
kind: Pod
metadata:
  name: badpod
spec:
  containers:
  - name: sise
    image: mhausenblas/simpleservice:0.5.0
    ports:
    - containerPort: 9876
    env:
    - name: HEALTH_MIN
      #value: "2000"
      value: "1"
    - name: HEALTH_MAX
      #value: "4000"
      value: "2"
    livenessProbe:
      initialDelaySeconds: 1
      periodSeconds: 2
      httpGet:
        path: /health
        port: 9876
